fos_ck_editor:
    configs:
        my_config_1:
            toolbar: "my_config"
            language : fr
    toolbars:
        configs:
            my_config: [ "@document", "-", "@full.paragraph", "-", "@full.styles" ]
        items:
            document: [ "Bold", "-", "Italic", "-", "Strike", "-", "RemoveFormat", "-", "full.paragraph", "-", "Link", "-", "Unlink", "-", "Image" ]
twig:
    form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'